### PR TITLE
Download the glid3xl latent diffusion weights at runtime, only if required, so that the image size will fit on docker repository

### PR DESCRIPTION
**Pull request by AmericanPresidentJimmyCarter**
After this update, the size of the image is much less than 20 GB.

```
REPOSITORY    TAG                               IMAGE ID       CREATED          SIZE
dalle-test    latest                            68fe8693a0e4   14 minutes ago   13.3GB
```

### CODE REVIEW

**Comment by delgermurun** [comment]
Nice work @AmericanPresidentJimmyCarter!

There is one thing, it downloads files each time `docker run ...`.
Can we attach a volume and re-use already downloaded files?

**Comment by AmericanPresidentJimmyCarter** [comment]
Sure thing, I can add some instructions for use of a volume too.

**Comment by AmericanPresidentJimmyCarter** [comment]
@delgermurun Ready to go

**Comment by delgermurun** [comment]
Nice solution! Great work as always. Thank you!

**Pull request merged**
