### PR TITLE
Revert "Add dalle2-laion to inference engine"

### PR DESCRIPTION
**Pull request by delgermurun**
Reverts jina-ai/dalle-flow#72

### CODE REVIEW

**Comment by AmericanPresidentJimmyCarter** [comment]
Did you have some trouble with it? Perhaps something that worked on my local env didn't replicate, or it used too much memory? It's odd that it was merged and then immediately reverted.

**Comment by delgermurun** [comment]
It works fine. I also run it locally. The only reason is that it uses too much RAM.
It's not a good idea to have the same kinds of big models unless we have an easy way to switch between them.

**Comment by AmericanPresidentJimmyCarter** [comment]
Right, no problem. I noticed that the new model (3b) requires way too much RAM to be useful for most consumer GPUs, so I guess it should be shelved until they've quantized the model to make it fit better.

**Comment by JoanFM** [comment]
The main problem @AmericanPresidentJimmyCarter is that the model was added to the same Flow. So the Flow was leveraging 2 of the models. This is way too much. It would be cool to have it as an option but not to share the 2 models in parallel.

**Pull request merged**
