### PR TITLE
Update to latest stable-inference version, fix downloading CLIP weights (Closes #124)

### LINKED ISSUE #124: Error with stable-diffusion model - FileNotFoundError
Hi, 
I tried to install stable diffusion model to my local server, but I encountered this error when I run 
`jina flow --uses flow.tmp.yml`

`FileNotFoundError: [Errno 2] No such file or directory: '/home/tyler/.cache/huggingface/hub/models--openai--clip-vit-large-patch14/refs/main'`

Also I tried this simple script too. 

```python
from stable_inference import StableDiffusionInference

stable_diffusion_module = StableDiffusionInference(
    checkpoint_loc='PATH',
    height=512,
    max_n_subprompts=8,
    max_resolution=589824,
    n_iter=1,
    use_half=True,
    width=512,
)
```
but the same error happened. 
I used this lib for stable-inference.
stable-inference @ git+https://github.com/AmericanPresidentJimmyCarter/stable-diffusion.git@v0.0.11

### PR DESCRIPTION
**Pull request by AmericanPresidentJimmyCarter**
There is a bug in my branch where CLIP weights do not download automatically. This updates to the latest version where they do.

### CODE REVIEW

**Comment by AmericanPresidentJimmyCarter** [comment]
@JoanFM Patch you were looking for.

**Comment by samsja** [comment]
The clip for the CLIP weight come from this commit in your repo right ? https://github.com/AmericanPresidentJimmyCarter/stable-diffusion/commit/09071dacab79b57a7ff28c01ecf2755127756438

**Review by samsja — APPROVED** [review]
lgtm

**Comment by AmericanPresidentJimmyCarter** [comment]
Correct, it's tagged [v0.0.12](https://github.com/AmericanPresidentJimmyCarter/stable-diffusion/releases/tag/v0.0.12)

**Review by JoanFM — APPROVED** [review]

**Pull request merged**
