### PR TITLE
Add new k-diffusion samplers to stable executor

### PR DESCRIPTION
**Pull request by AmericanPresidentJimmyCarter**
This adds the newest samplers from k-diffusion into the stable executor along with the ability to choose a default noise schedule for the diffusion unet steps.

From k-diffusion: "[DPM-Solver++(2S) and (2M)](https://arxiv.org/abs/2211.01095) are implemented now too for improved quality with low numbers of steps."

### CODE REVIEW

**Comment by AmericanPresidentJimmyCarter** [comment]
This also fixes a Dockerfile issue due to jax being too low of a version for transformers. The jax version has been bumped to `0.3.24`.

**Comment by samsja** [comment]
Can you do the jax bump in a separate PR ?

**Comment by AmericanPresidentJimmyCarter** [comment]
@samsja It has been split out.

**Review by samsja — APPROVED** [review]
lgtn

**Pull request merged**
